# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Admin\Desktop\Src\Files_Project\pmv1\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 326)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/root/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 3, 1, 1)
        self.viewlabel = QtWidgets.QLabel(self.centralwidget)
        self.viewlabel.setStyleSheet("background-color:white")
        self.viewlabel.setText("")
        self.viewlabel.setObjectName("viewlabel")
        self.gridLayout.addWidget(self.viewlabel, 1, 0, 1, 4)
        self.dirEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dirEdit.setObjectName("dirEdit")
        self.gridLayout.addWidget(self.dirEdit, 0, 0, 1, 3)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 2, 2, 1, 2)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuControl.addAction(self.actionPlay)
        self.menuControl.addAction(self.actionStop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "媒体查看器"))
        self.openButton.setText(_translate("MainWindow", "打开"))
        self.stopButton.setText(_translate("MainWindow", "暂停视频"))
        self.playButton.setText(_translate("MainWindow", "播放视频"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuControl.setTitle(_translate("MainWindow", "控制(&C)"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionExit.setText(_translate("MainWindow", "退出(&X)"))
        self.actionPlay.setText(_translate("MainWindow", "播放(&P)"))
        self.actionStop.setText(_translate("MainWindow", "暂停(&S)"))
import file_rc
